@Assignment_8_HostAddress = http://localhost:5191

GET {{Assignment_8_HostAddress}}/
Accept: application/json

###


GET {{Assignment_8_HostAddress}}/movies/1
Accept: application/json

###

POST {{Assignment_8_HostAddress}}/movies
Content-Type: application/json

{
  "Title": "The Matrix",
  "ReleaseDate": "1999-03-31",
  "Genre": "Sci-Fi",
  "Price": 9.99,
  "Rating": 95,
  "PictureUri": "https://example.com/matrix.jpg"
}


###

DELETE {{Assignment_8_HostAddress}}/movie/7
Accept: application/json

###

PUT {{Assignment_8_HostAddress}}/movie
Content-Type: application/json

{
  "Id": 9,
  "Title": "The Matrix Reloaded",
  "ReleaseDate": "2003-05-15",
  "Genre": "Sci-Fi Action",
  "Price": 12.99,
  "Rating": 85,
  "PictureUri": "https://example.com/matrix-reloaded.jpg"
}


### 


